#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# To apply term's opacity to SpaceVim add the following to ~/.Spacevim/config/init.vim
# -----
# func! s:transparent_background()
#   highlight Normal guibg=NONE ctermbg=NONE
#   highlight NonText guibg=NONE ctermbg=NONE
#   highlight EndOfBuffer guibg=NONE ctermbg=NONE
# endf
# autocmd ColorScheme * call s:transparent_background()
# -----

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    
    # colorscheme = "vim-material"
    colorscheme = "material"
    colorscheme_bg = "dark"    
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    # windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true ## was false
    statusline_unicode_symbols = true
    enable_vimfiler_gitstatus = true ## Extra
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true #added
    filemanager = "nerdtree"
    sidebar_direction = 'left'

    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

#    highlight Normal guibg=NONE ctermbg=NONE
#    highlight NonText guibg=NONE ctermbg=NONE
#    highlight EndOfBuffer guibg=NONE ctermbg=NONE

# Enable autocomplete layer

[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "nil"
  auto_completion_tab_key_behavior = "nil"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

#### Custom 
[[layers]]
  name = "lang#ruby"

#[[custom_plugins]]
#  repo = "hzchirs/vim-material"
#  merged = 0

[[custom_plugins]]
  repo = "mhartington/oceanic-next"
  merged = 0

[[custom_plugins]]
  repo = "liuchengxu/space-vim-dark"
  merged = 0

[[custom_plugins]]
  name = "dracula/vim"

[[layers]]
  name = "git"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "sh"

[[layers]]
  name = "VersionControl"

#[[layers]]
#  name = "tools"

#[[layers]]
#  name = "unite"

#[[layers]]
#  name = "lang#c"

#[[layers]]
#  name = "lang#latex"

#[[layers]]
#  name = "chinese"
#
[[layers]]
  name = "default"
#
#[[layers]]
#  name = "tools#dash"

#[[custom_plugins]]
#  name = 'dag/vim-fish'
#  # note: you need to disable merged feature
#  merged = false


